name: 'Driftive'
description: 'Driftive detects state drifts in Terragrunt projects'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  slack-url:
    description: 'Slack webhook URL, for notifications'
    required: true
  concurrency:
    description: 'Number of parallel projects to scan'
    required: true
    default: "1"
  distribution:
    description: 'terraform distribution. Default is "tf". Options are "tf" for Terraform, "tofu" for OpenTofu.'
    required: false
    default: "tf"
  distribution-version:
    description: 'terraform distribution version. Default is "latest"'
    required: false
    default: "latest"
  terragrunt-version:
    description: 'terragrunt version. Default is "latest"'
    required: false
    default: "latest"
runs:
  using: 'docker'
  image: Dockerfile
  args:
    - ${{ inputs.slack-url }}
    - ${{ inputs.concurrency }}
    - ${{ inputs.distribution }}
    - ${{ inputs.distribution-version }}
    - ${{ inputs.terragrunt-version }}
