name: 'Driftive'
description: 'Driftive detects state drifts in Terraform/Terragrunt/OpenTofu projects'
branding:
  icon: loader
  color: blue
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  slack-url:
    description: 'Slack webhook URL, for notifications'
    required: false
  concurrency:
    description: 'Number of parallel projects to scan'
    required: true
    default: "1"
  distribution:
    description: 'terraform distribution. Default is "tf". Options are "tf" for Terraform, "tofu" for OpenTofu.'
    required: false
    default: "tf"
  distribution-version:
    description: 'terraform distribution version. Default is "latest"'
    required: false
  distribution-version-file:
    description: 'File containing the version spec of the version to use.  Example: .tool-versions.'
    required: false
  terragrunt-version:
    description: 'terragrunt version. Default is "latest"'
    required: false
  terragrunt-version-file:
    description: 'File containing the version spec of the version to use.  Example: .tool-versions.'
    required: false
  log-level:
    description: 'log level. Default is "info"'
    required: false
    default: "info"
  enable-stdout-output:
    description: 'enable stdout output. Default is "true"'
    required: false
    default: "true"
  exit-code:
    description: 'set to true to exit with code 1 if drifts are detected. Default is "false"'
    required: false
    default: "false"
runs:
  using: 'docker'
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    SLACK_URL: ${{ inputs.slack-url }}
    CONCURRENCY: ${{ inputs.concurrency }}
    LOG_LEVEL: ${{ inputs.log-level }}
    STDOUT_OUTPUT: ${{ inputs.enable-stdout-output }}
    EXIT_CODE: ${{ inputs.exit-code }}

    TERRAFORM_DISTRIBUTION: ${{ inputs.distribution }}
    TERRAFORM_DISTRIBUTION_VERSION: ${{ inputs.distribution-version }}
    TERRAFORM_DISTRIBUTION_VERSION_FILE: ${{ inputs.distribution-version-file }}
    TERRAGRUNT_VERSION: ${{ inputs.terragrunt-version }}
    TERRAGRUNT_VERSION_FILE: ${{ inputs.terragrunt-version-file }}
